firmata/arduino

- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataYun/StandardFirmataYun.ino
- extras/revisions.txt
Fixes an issue where analog values were being reporting every time system reset was called.
> prevent analog reporting during system reset

- Firmata.cpp
- Firmata.h
- examples/StandardFirmata/StandardFirmata.ino
- utility/AnalogInputFirmata.cpp
Fixes an issue where all analog pins values are reported when systemReset is called, even if no analog pins are used. This was crashing at least one client library (PyMata) and sending noise for any unused analog input.
> prevent analog reporting from system reset function

- Firmata.cpp
- Firmata.h
- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataYun/StandardFirmataYun.ino
- extras/revisions.txt
- library.properties
- release.sh
Adds the SET_DIGITAL_PIN_VALUE message.
reopened against v2.5.beta1 instead of master branch
> implemented set digital pin value feature

- Boards.h
- examples/StandardFirmataChipKIT/LICENSE.txt
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
Adding chipKIT board support to Firmata.
> Chip kit support

- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataYun/StandardFirmataYun.ino
However users must be careful to not set the min value to lower than what their board can handler per the number of operations it runs per loop. General rule, if lower the value and the board starts acting weird, raise the value until you no longer observe issues.
> lower min sampling interval to 1ms

- Firmata.cpp
- Firmata.h
- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataYun/StandardFirmataYun.ino
Implements the protocol for [setting a digital pin value](https://github.com/firmata/protocol/blob/master/protocol.md#message-types).
Was previously in the v2.5.beta1 branch but needed to merge other commits from that branch earlier.
This PR adds a new feature so it will require bumping the Firmata minor version when merged.
> implement protocol to set digital pin value

- Boards.h
This adds a definition to Boards.h for the Pinoccio Scout, an Arduino compatible device similar to the Mega, as seen here: https://pinocc.io/
> Adding Pinoccio Scout to Boards.h

- Boards.h
- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataYun/StandardFirmataYun.ino
You will need an official Arduino Pro Zero board. Do not get an M0 Pro board, that will not work with Firmata.
In order to use, you'll have to make sure the Servo library is at least version 1.1.0.  Follow these instructions:
1. In the Arduino IDE (the arduino.cc one), go to Sketch > Include libraries > Manage libraries.
2. Search for "Servo" and scroll down the results list to "Servo by Michael Margolis..."
3. Tap on the list item (I wish this was more clear in the UI), then an option to Update will appear
4. Click on update.
TODO:
> Add support for Arduino Zero

- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
> enable option to auto restart i2c transmission per issue #82

- Boards.h
- Firmata.h
- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
Adds support for the Arduino 101. Only Serial and Ethernet transports for now. [BLE to be added later (hopefully)](https://github.com/firmata/arduino/issues/251).
> add Arduino 101

- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- readme.md
- utility/EthernetClientStream.cpp
- utility/EthernetClientStream.h
refactor to eliminate Firmata-related compiler warnings showing up for Arduino 101 (which appears to have stricter flags set than other boards).
> eliminate Firmata related compiler warnings

- Firmata.cpp
- Firmata.h
This is an alternative approach to: https://github.com/firmata/arduino/pull/247/files. However neither approach allows the user to override `VERSION_BLINK_PIN` if it is specified already in Boards.h for the board they are compiling against. This is because `VERSION_BLINK_PIN` is defined per board (that have an onboard LED) in Boards.h and Firmata.cpp includes Boards.h, so there is no way to `undef` `VERSION_BLINK_PIN` from the user's sketch.
> make VERSION_BLINK_PIN optional

- Boards.h
- Firmata.cpp
- Firmata.h
- examples/AllInputsFirmata/AllInputsFirmata.ino
- examples/AnalogFirmata/AnalogFirmata.ino
- examples/EchoString/EchoString.ino
- examples/ServoFirmata/ServoFirmata.ino
- examples/SimpleAnalogFirmata/SimpleAnalogFirmata.ino
- examples/SimpleDigitalFirmata/SimpleDigitalFirmata.ino
- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- extras/revisions.txt
- library.properties
- readme.md
- release.sh
- test/firmata_test/firmata_test.ino
Separate protocol version and firmware (library) version.
> Bump version to 2.5.1.

- Firmata.cpp
- Firmata.h
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- keywords.txt
This provides a way to bypass the version blink sequence on startup. As the minor version gets longer, so does this blocking blink sequence. This only applies when using the default Serial transport (since blinkVersion is not called when passing a `Stream` reference to `Firmata.begin(stream)`. In other works there is no need to disable for Ethernet, WiFi or other non-Serial variants.
By default the blink sequence will still run unless `Firmata.disableBlinkVersion()` is called before `Firmata.begin()` or `Firmata.begin(baud)`.
StandardFirmataPlus now disables the blink sequence. I've kept it in StandardFirmata however due to user expectations (and there are likely instructions for looking for the sequence when running StandardFirmata).
> provide a way to bypass the version blink sequence

- Boards.h
- Firmata.cpp
- examples/StandardFirmataBLE/LICENSE.txt
- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataBLE/bleConfig.h
- utility/BLEStream.cpp
- utility/BLEStream.h
Adds StandardFirmataBLE for Arduino 101. Should also work with the RedBearLab BLE Shield (v2) when paired with a board with sufficient memory (Zero, Due, Mega). Works with RedBearLab BLE Nano with modifications ([detailed here](https://gist.github.com/soundanalogous/d39bb3eb36333a0906df)).
To use with the Arduino 101, you must install the Intel Curie Boards v1.0.5 package via the Arduino Boards Manager. Reporting of analog input values and I2C read (when using READ_CONTINUOUS mode) will be slow (~150ms interval). You can greatly speed things up however by manually patching the CurieBLE library via the [instructions here in StandardFirmataBLE.ino](https://github.com/firmata/arduino/blob/ble/examples/StandardFirmataBLE/StandardFirmataBLE.ino#L759-L773).
An example firmata.js (node.js) …
> Intial BLE support for Arduino 101 and some BRL boards

- Boards.h
- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernetPlus/StandardFirmataEthernetPlus.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
to support different ESP8266 boad layouts, use board depended constants
from "...\esp8266\hardware\esp8266\2.1.0\variants\...\pins_arduino.h"
DOUT, DIN, I2C and SERIAL0 have been tested and are working with a HUZZA board
> pin functions based on board depended defaults

- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
- examples/StandardFirmataWiFi/wifiConfig.h
- utility/WiFiClientStream.h
- utility/WiFiServerStream.h
- utility/WiFiStream.h
Changes
- server related functions moved from WiFiStream into WiFiServerStream
- unified class interface for sketch file (no client/server defines)
- WiFi and TCP configuration and connect split into individual methods (TCP constructor, static IP config, WiFi begin and TCP maintain)
- WiFi only initialized once at startup (WiFi connections cannot be forced by repeatedly calling begin)
- convenience methods for combined WiFi/network initialization removed
Tests
- tested with Huzzah ESP8266 in client mode
- successfully builds for AVR architecture with legacy WiFi option
Todo
- decide if inheritance from new WiFiStream is preferable to copied code in two classes in regard to code efficiency, code size, platform compatibility and maintenance
- decide if a single client/server class would be …
> WiFiClientStream added

- utility/WiFiClientStream.h
- utility/WiFiServerStream.h
- utility/WiFiStream.h
- check member _connected first in connect_client() to prevent querying
connected() of disconnected _client
- added method status() to check TCP connection state (ESP8266 only)
> connection state management modified

- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
- examples/StandardFirmataWiFi/wifiConfig.h
- split wifi init and firmata init into separate functions
- add hostConnectionCallback
> refactor setup function

- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
- examples/StandardFirmataWiFi/wifiConfig.h
- utility/WiFiClientStream.h
- utility/WiFiServerStream.h
- utility/WiFiStream.h
Adds ability to setup board as a TCP client or TCP server.
> Add TCP client and ability to choose between TCP client and Server

- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataBLE/bleConfig.h
Intel finally released v1.0.6 of the Intel Curie Boards package which includes the `setConnectionInterval` implementation.
> enable CurieBLE.setConnectionInterval

- readme.md
Bitbucket repository [says](https://bitbucket.org/thomasweinert/carica-firmata/src) that it was moved to the GitHub. This pull request actualizes the URL.
> Update url of ThomasWeinert/carica-firmata

- readme.md
This PR adds a Rust language Firmata client library to the README and rewrites "golang" to simply "Go."
> Add Rust firmata client library

- Firmata.cpp
- Firmata.h
- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
- utility/SerialFirmata.cpp
- utility/SerialFirmata.h
Firmata should now compile without errors back to Arduino IDE version 1.0.6 (for the 1.0.x series) and version 1.5.8 for the (1.5.x / 1.6.x series). I haven't tried on anything older than 1.0.6 or 1.5.8.
> Fix compiler issues for older Arduino IDE versions

- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
Only disable PWM when setting pinMode to OUTPUT if pin mode was previously set to PWM.
Needs to be thoroughly tested with a few Firmata clients to make sure this doesn't introduce any undesired side effects. That will determine whether or not this change should be marked as a bug fix or if it necessitates as a minor version update.
> Only disable PWM if previously enabled

- FirmataParser.cpp
Addresses issue #322 
Passes all tests I have available
> Update FirmataParser to support older compilers

- Firmata.cpp
- Firmata.h
- FirmataParser.cpp
- FirmataParser.h
This is ready for testing. I haven't had any opportunity to test this between hardware, but it does pass the test suite.
I wanted to share what I'm working on, so I could get feedback. I think it resolves the memory allocation concerns @soundanalogous pointed out in issue #328, and it can also handle my desire to utilize `realloc()`.
I will report back once I've had an opportunity to test.
[EDIT] I have confirmed it works with Windows Remote Arduino.
[EDIT] I have confirmed it works as expected on Linux.
> Abstract FirmataParser memory allocation scheme

- Boards.h
Adds support for the new [Arduino MKRZero](https://www.arduino.cc/en/Main/ArduinoBoardMKRZero) board.
This board has some gaps in the usable pins, the built-in LED is on pin 32 and the ADC for the battery is on pin 33. Pins 22 - 31 are used for USB, AREF, the SD card reader (SPI), and a pad on the bottom of the board.
> Add support for Arduino MKRZero

- Firmata.cpp
- Firmata.h
- FirmataMarshaller.cpp
- FirmataMarshaller.h
This commit is intended to be the first of many addressing any missing APIs listed in issue #349
> Complete base API

- utility/BLEStream.h
Arduino and Intel are working on a new API for CurieBLE, progress can be seen here: https://github.com/01org/corelibs-arduino101/pull/337
There's a backwards compatibility layer with the existing BLEPeripheral based API, so for the most part no code changes will be needed for CurieBLE users once they upgrade.
However, we've overloaded `BLECharacteristic::setEventHandler(...)` with the following:
```
typedef void (*BLECharacteristicEventHandler)(BLEDevice bledev, BLECharacteristic characteristic);
typedef void (*BLECharacteristicEventHandlerOld)(BLECentral &central, BLECharacteristic &characteristic);
void setEventHandler(BLECharacteristicEvent event, 
BLECharacteristicEventHandler eventHandler);
void setEventHandler(BLECharacteristicEvent event, 
BLECharacteristicEventHandlerOld …
```
> Add cast for compatibility with the next version of CurieBLE

- Firmata.cpp
- Firmata.h
- FirmataParser.cpp
- FirmataParser.h
This provides maximum functionality without breaking API compatibility or a change in existing usage.
This works for `REPORT_FIRMWARE`, because it is wrapped in a sysex message. A sysex is parsed in its entirety before being processed, which allows us to uniformly invoke the callback and discard buffered bytes (or manage their absence) as we see fit.
This is tested and confirmed on the ESP8266, Uno and 101.
> firmware callbacks

- Boards.h
Hi,
I'm the software developer of the Arduino Primo board. I would like to add the support for this board in your library.
Thanks.
> Added support for Arduino Primo board

- test/readme.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- Boards.h
This adds support for the new Arduino MKRFox1200 board.
Please note that this board is only available in Europe for now, see: https://blog.arduino.cc/2017/04/18/introducing-the-arduino-mkrfox1200/
@agdl has briefly tested this change on with a MKRFox1200 and Johny-Five.
> Add support for Arduino MKRFox1200

- Boards.h
Hi,
This PR add the support of STM32 MCU based board.
More information here: [STM32 cores enabled in Arduino IDE](https://community.st.com/community/stm32-community/blog/2017/02/02/stm32-cores-enabled-in-arduino-ide)
Latest release of the [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32) is functional with Firmata. The modified lib with ARDUINO_ARCH_STM32 is currently released with the core and could be removed when this PR will be merged.
Core is provided as a package thanks the Arduino Boards manager, see the [wiki](https://github.com/stm32duino/wiki/wiki/Getting-Started)
Thanks in advance
> Add support for STM32 MCU based boards

- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataEthernet/ethernetConfig.h
- utility/EthernetServerStream.cpp
- utility/EthernetServerStream.h
server mode implemented.
For server mode remote_ip, remote_host and remote_port should not be
defined.
Instead the server_port has to be defined.
> added server mode to StandardFirmataEthernet

- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- utility/EthernetClientStream.h
- utility/EthernetServerStream.h
Adds a couple more debug statements to help diagnose any minor connectivity issues.
> Improve StandardFirmataEthernet logging

- Boards.h
This Boards.h modification add support for Adafruit nrf52 board series.
https://www.adafruit.com/product/3406
Unfortunately our ble API is a bit different than the currently one used in examples/StandardFirmataBLE.ino
Thus we have to make separate sketch in our example repo.
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/develop/libraries/Bluefruit52Lib/examples/Peripheral/StandardFirmataBLE/StandardFirmataBLE.ino
But this patch will allow user to compile without us including a separated fork
> add Adafruit nrf52 boards support

- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
The current implementation pulls bytes out of the sysex buffer, regardless of whether or not the user specified such bytes.
> Fix I2C config parameter interpretation

- Boards.h
AEND is an internal STM32 core constant and should not be used.
Replaced by (A0 + TOTAL_ANALOG_PINS)
> [STM32] Avoid using non standard constant

- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataBLE/bleConfig.h
- utility/BLEStream.h
- utility/BluefruitLE_SPI_Stream.cpp
- utility/BluefruitLE_SPI_Stream.h
These changes add support for the [Adafruit Feather M0 Bluefruit LE](https://www.adafruit.com/product/2995) board to StandardFirmataBLE.  They should also work with other Bluefruit LE boards/modules that communicate with the nRF51822 via SPI, although I've only tested the Feather M0.  The changes require a few [small modifications](https://github.com/cstawarz/Adafruit_BluefruitLE_nRF51/tree/firmata_fixes) to the Adafruit BluefruitLE nRF51 package (pull request: adafruit/Adafruit_BluefruitLE_nRF51#43).
I also moved the configuration of the BLE connection and flush intervals to bleConfig.h and updated the connection interval values for the Arduino 101 (which, as of Intel Curie Boards package v2.0.2, must be given in units of milliseconds, not 1.25ms).
I tested the changes on both an Arduino …
> Add support for Adafruit Feather M0 Bluefruit LE to StandardFirmataBLE

- Boards.h
I've based this on the MKR FOX 1200 definition, and left the highest pin as 32 for the battery ADC. There more pins above 32 defined in the variants but they are used for the LoRaWAN and cellular modules on the boards.
Variants for the new boards are available with the new Arduino SAMD 1.6.17 core release:
* https://github.com/arduino/ArduinoCore-samd/blob/master/variants/mkrwan1300/variant.h
* https://github.com/arduino/ArduinoCore-samd/blob/master/variants/mkrgsm1400/variant.h
> Add support for Arduino MKR WAN 1300 and MKR GSM 1400

- keywords.txt
The third field of keywords.txt is used to provide Arduino Language/Libraries Reference links, which are accessed from the Arduino IDE by highlighting the keyword and then selecting "Find in Reference" from the Help or right click menu. Adding values to this field that do not match any existing reference pages results in a "Could not open the URL" error.
Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywordstxt-format
> Remove invalid reference links from keywords.txt

- Boards.h
Ran into this issue when compiling Marlin v2 for the Creality Ender-3
See also #281
> Support for Sanguino/Melzi, e.g. Creality Ender-3

- Boards.h
- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
- examples/StandardFirmataWiFi/wifiConfig.h
@dowlingw @eccoscreen 
The board uses the U-Blox WiFi NINA chip which has an ESP32 inside running
NINA firmware. The SAMD21 is connected to the U-Blox chip via SPI. The
WiFININA library is used to communicate between the U-Blox chip and the
SAMD21. Other boards use the same U-Blox chip such as the MKR Vidor 4000
and the Uno WiFi Rev2. Additional changes will be required to support
those boards. See #407
> Add support for Arduino MKR WiFi 1010

- examples/StandardFirmataBLE/bleConfig.h
When interacting with StandardFirmataBLE running on an Adafruit Feather M0 Bluefruit LE from iPhone's and iPad's running iOS 12.2, the BLE connection was regularly dropped 15-20 seconds after being established.  These changes to the connection intervals resolved the issue.  (The specific values are based on [Apple's recommendations](https://developer.apple.com/library/archive/qa/qa1931/_index.html).)
> Adjusted Bluefruit LE connection intervals for better compatibility with Apple devices

- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataBLE/bleConfig.h
- utility/BluefruitLE_SPI_Stream.h
By default, the BLE firmware on the Adafruit Feather M0 Bluefruit LE will switch from fast advertising (20ms interval) to low-power advertising (417.5ms interval) after 30 seconds.  I found that, after the switch to low-power advertising, connection attempts from macOS devices often failed (despite the fact that such a switch is explicitly condoned in [Apple's documentation](https://developer.apple.com/library/archive/qa/qa1931/_index.html)).
These changes alter the default configuration of Bluefruit LE devices to always use the initial, 20ms advertising interval.  They also introduce a new preprocessor macro, `FIRMATA_BLE_ADVERTISING_INTERVAL`, which can be set by other device configurations.  Users who want to stick with the Feather M0's default advertising behavior can simply comment …
> Set Bluefruit LE advertising interval

- Firmata.h
Firmata/Firmata.h:131:17: error: friend declaration of 'void encodeByteStream(size_t, uint8_t*, size_t) const' specifies default arguments and isn't a definition [-fpermissive]
131 |     friend void FirmataMarshaller::encodeByteStream (size_t bytec, uint8_t * bytev, size_t max_bytes = 0) const;
|                 ^~~~~~~~~~~~~~~~~
Ref:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2000/n1263.html
Fixes #437
> Fix build issue with arm none eabi gcc v9.2.1

- Boards.h
Hi,
This PR update the Boards.h definition for the STM32 core.
Since the release 1.8.0, the analog pins can be not contiguous.
That's why, I defined 2 new functions at core level:
* `pinIsAnalogInput`
* `digitalPinToAnalogInput`
I also add a check to the core version to ensure backward compatibility.
Thanks
> STM32 update

- Boards.h
Hi @soundanalogous 
This PR fixes an issue with version checking I've added in my previous PR for the STM32 targets.
Thanks.
BR
> [STM32] Fix version checking

- examples/StandardFirmata/StandardFirmata.ino
- examples/StandardFirmataBLE/StandardFirmataBLE.ino
- examples/StandardFirmataChipKIT/StandardFirmataChipKIT.ino
- examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
- examples/StandardFirmataPlus/StandardFirmataPlus.ino
- examples/StandardFirmataWiFi/StandardFirmataWiFi.ino
Same as https://github.com/firmata/ConfigurableFirmata/pull/94. 
Tested for StandardFirmata.
> Return only as many bytes as were received in I2C transfers.

- utility/SerialFirmata.h
FIRMATA_SERIAL_RX_DELAY being defined by default resulted [SERIAL_RX_BUFFER_SIZE not being defined](https://github.com/firmata/arduino/blob/e385ece47cfe361f36714fa7f20552058d0229ea/utility/SerialFirmata.cpp#L364) for Arduino M0 boards, resulting in a compile error. Temporary fix is to keep FIRMATA_SERIAL_RX_DELAY commented out by default.
@jnsbyr FYI.
> Fix compile error for M0 boards

- readme.md
The link to https://github.com/ThomasWeinert/carica-firmata was empty so it linked nowhere. Updated to actually link to the URL.
> Add missing link for PHP Client "carica"

- Boards.h
This change adds support for the [Arduino Nano 33 BLE](https://store.arduino.cc/usa/nano-33-ble) to Boards.h.
> Add support for Arduino Nano 33 BLE

- examples/StandardFirmataBLE/bleConfig.h
- utility/ArduinoBLE_UART_Stream.cpp
- utility/ArduinoBLE_UART_Stream.h
- utility/BluefruitLE_SPI_Stream.cpp
These changes extend StandardFirmataBLE to work with boards supported by the [ArduinoBLE](https://www.arduino.cc/en/Reference/ArduinoBLE) library.  I've only tested on the [Nano 33 IoT](https://docs.arduino.cc/hardware/nano-33-iot), but any other ArduinoBLE-compatible board should work, too.
> Add support for ArduinoBLE devices to StandardFirmataBLE

- readme.md
exchanged outdated link with new link.
would be great if someone could also update this here: http://firmata.org/wiki/Download
found outdated mentions also here: 
* https://github.com/firmata/arduino/blob/c285135275c4dd4f0d0bbf82da3c5844a29eaf07/docs/html/index.html#L183
* https://github.com/firmata/arduino/blob/c285135275c4dd4f0d0bbf82da3c5844a29eaf07/docs/html/md_readme.html#L183
but wasn't sure if those should be edited manually?
> Fixed link to vvvv/VL implementation

- Boards.h
This pull request allows Boards.h to automatically detect Teensy 4.0 vs Teensy 4.1 without requiring the user to manually define anything.  No actual code is changed, only the `#if defined()` checks are updated to the names which are automatically defined within the Arduino environment.
> Improve defines for Teensy 4.0 and Teensy 4.1
